version: "3.9"
services:
  util:
    container_name: epsagon_util
    build:
      dockerfile: Dockerfile_util
    pull_policy: build
    image: epsagon_util_image:latest
    ports:
      - 5000:5000
    volumes:
      - EpsagonUtilVolume:/app
volumes:
  EpsagonUtilVolume:
    external: false
    name: EpsagonUtilVolume
