version: "3.9"
services:
#  onlinebuild:
#    container_name: onlinewithvolume
#    image: revelare/autobuildtest:latest
#    pull_policy: always
#    ports:
#      - 5000:5000
#    volumes:
#      - TestVolume:/app
  localbuild:
    container_name: epsagon_container
    build:
      dockerfile: Dockerfile
    pull_policy: build
    image: epsagon_dev:latest
    ports:
      - 5000:5000
    volumes:
      - EpsagonVolume:/app
volumes:
  EpsagonVolume:
    external: false
    name: EpsagonVolume