version: "3.9"
services:
  sdk:
    container_name: epsagon_container
    build:
      dockerfile: Dockerfile_util
    pull_policy: build
    image: epsagon_dev:latest
    ports:
      - 5000:5000
    volumes:
      - EpsagonVolume:/app
  util:
    container_name: epsagon_container
    build:
      dockerfile: Dockerfile_util
    pull_policy: build
    image: epsagon_dev:latest
    ports:
      - 5000:5000
    volumes:
      - EpsagonVolume:/app
volumes:
  EpsagonVolume:
    external: false
    name: EpsagonVolume