name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "latest"
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: courses
          git-user: KarimGabsi
          git-password: ${{ secrets.TOKEN }}
          deployment-branch: main