name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: courses
          git-user: KarimGabsi
          git-password: ${{ secrets.TOKEN }}
          deployment-branch: main